/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;

/**
 *
 * @author Usuario iTC
 */
public class HotelInter extends javax.swing.JFrame {

    /**
     * Creates new form HotelInter
     */
    public HotelInter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bgpnl = new javax.swing.JPanel();
        lblnombreH = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblfondo = new javax.swing.JLabel();
        lblLogoH = new javax.swing.JLabel();
        lblIniciar = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblusuario1 = new javax.swing.JLabel();
        txtUsuario1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        psContraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/hotel2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Camerum");
        setBackground(new java.awt.Color(0, 102, 153));
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        setLocationByPlatform(true);

        bgpnl.setBackground(new java.awt.Color(255, 255, 255));
        bgpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnombreH.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblnombreH.setForeground(new java.awt.Color(255, 255, 255));
        lblnombreH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnombreH.setText("CAMERUM");
        bgpnl.add(lblnombreH, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 290, 40));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        bgpnl.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 290, 170));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/city.png"))); // NOI18N
        bgpnl.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 370));

        lblLogoH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLogoH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/favicon.png"))); // NOI18N
        lblLogoH.setText("CAMERUM HOTEL");
        bgpnl.add(lblLogoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblIniciar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblIniciar.setText("INICIAR SESIÓN");
        bgpnl.add(lblIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, 30));

        lblcontraseña.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblcontraseña.setText("CONTRASEÑA");
        bgpnl.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        bgpnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, 40));

        lblusuario1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblusuario1.setText("USUARIO");
        bgpnl.add(lblusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario1.setText("Ingrese su nombre de usuario");
        txtUsuario1.setBorder(null);
        txtUsuario1.setCaretColor(new java.awt.Color(204, 204, 204));
        bgpnl.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 260, -1));
        bgpnl.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, 40));

        psContraseña.setText("jPasswordField1");
        psContraseña.setBorder(null);
        bgpnl.add(psContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bgpnl.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bgpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelInter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgpnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIniciar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoH;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblnombreH;
    private javax.swing.JLabel lblusuario1;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField txtUsuario1;
    // End of variables declaration//GEN-END:variables
}
