# Generated by Django 4.0.6 on 2022-08-16 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banio',
            fields=[
                ('numero_duchas', models.PositiveSmallIntegerField(help_text='numero de duchas')),
                ('banio_id', models.PositiveSmallIntegerField(help_text='numero de baño', primary_key='baño-id', serialize=False)),
                ('elementos_de_aseo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('precio_bar', models.FloatField()),
                ('bar_id', models.PositiveIntegerField(primary_key='bar-id', serialize=False)),
                ('numero_bebidas_alcoholicas', models.PositiveIntegerField()),
                ('numero_bebidas_no_alcoholicas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('tipo_habitacion', models.CharField(max_length=50)),
                ('numero_camas', models.PositiveIntegerField(help_text='Ingrese el numero de camas de la Habitacion')),
                ('numero_banios', models.PositiveIntegerField(help_text='Ingrese el numero de baños de la Habitacion')),
                ('posee_mirador', models.BooleanField()),
                ('precio_habitacion', models.FloatField()),
                ('numero_habitacion', models.PositiveIntegerField(primary_key='habitacion-id', serialize=False)),
                ('precio_banio', models.PositiveIntegerField(blank=True)),
                ('banio_list', models.ManyToManyField(blank=True, related_name='banio_list', to='hotel.banio')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RealizarEvento',
            fields=[
                ('evento_id', models.PositiveIntegerField(primary_key='envento-id', serialize=False)),
                ('fecha', models.CharField(max_length=40)),
                ('duracion', models.CharField(max_length=70)),
                ('tipo_evento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('recepcion_id', models.PositiveIntegerField(primary_key='recepcion-id', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReservacionComida',
            fields=[
                ('almuerzo', models.CharField(max_length=150)),
                ('cena', models.CharField(max_length=150)),
                ('desayuno', models.CharField(max_length=150)),
                ('precio_almuerzo', models.FloatField()),
                ('precio_desayuno', models.FloatField()),
                ('precio_cena', models.FloatField()),
                ('desea_almuerzo', models.BooleanField()),
                ('desea_cena', models.BooleanField()),
                ('desea_desayuno', models.BooleanField()),
                ('reservacion_id', models.CharField(max_length=100, primary_key='reservacion-id', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvcable', models.BooleanField()),
                ('servicio_habitacion', models.BooleanField()),
                ('servicio_limpieza', models.BooleanField()),
                ('bar', models.BooleanField()),
                ('spa', models.BooleanField()),
                ('gim', models.BooleanField()),
                ('precio_bar', models.FloatField()),
                ('precio_spa', models.FloatField()),
                ('precio_gim', models.FloatField()),
                ('precio_servicio_limpieza', models.FloatField()),
                ('precio_tvcalbe', models.FloatField()),
                ('precio_servicio_habitacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='hotel.persona')),
                ('cliente_id', models.CharField(max_length=50, primary_key='cliente-id', serialize=False)),
            ],
            bases=('hotel.persona',),
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hotel.persona')),
                ('gerente_id', models.PositiveIntegerField()),
            ],
            bases=('hotel.persona',),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('precio_internet', models.FloatField()),
                ('numero_servicio', models.PositiveIntegerField(primary_key='servicio-id', serialize=False)),
                ('servicio_adicional', models.ManyToManyField(blank=True, related_name='servicioa_list', to='hotel.servicioadicional')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('numero_dias', models.PositiveIntegerField()),
                ('precio_Servicio', models.FloatField()),
                ('numero_huestes', models.PositiveIntegerField()),
                ('tiempo_estancia', models.PositiveIntegerField()),
                ('tipo_descuento', models.CharField(max_length=50)),
                ('numero_reservacion', models.PositiveIntegerField(primary_key='reservacion-id', serialize=False)),
                ('precio_reservacion', models.PositiveIntegerField(blank=True)),
                ('reservacion_comida_list', models.ManyToManyField(blank=True, related_name='reservacionComida_list', to='hotel.reservacioncomida')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('recepcionista_id', models.PositiveIntegerField(primary_key='recepcionista-id', serialize=False)),
                ('recepcionista', models.PositiveIntegerField()),
                ('reservacion', models.ManyToManyField(blank=True, related_name='reservacion_list', to='hotel.reservacion')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('numero_habitaciones', models.PositiveIntegerField(help_text='Ingrese el numero de habitaciones del Hotel')),
                ('numero_pisos', models.PositiveIntegerField(help_text='Ingrese el numero de pisos del Hotel')),
                ('posee_piscina', models.BooleanField(help_text='Desea reservar con piscina')),
                ('ruc', models.CharField(max_length=50, primary_key='ruc-id', serialize=False)),
                ('numero_estrellas', models.PositiveSmallIntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_inaguracion', models.CharField(max_length=50)),
                ('habitacion_list', models.ManyToManyField(blank=True, related_name='habitacion_list', to='hotel.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.PositiveIntegerField(primary_key='factura-id', serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=30)),
                ('valor_subtotal', models.FloatField(blank=True, null=True)),
                ('valor_total', models.FloatField(blank=True, null=True)),
                ('valor_iva', models.FloatField(blank=True, null=True)),
                ('habitacion_lista', models.ManyToManyField(blank=True, related_name='habitacion_lista', to='hotel.habitacion')),
            ],
        ),
    ]
