/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;


/**
 *
 * @author Usuario iTC
 */
public class Inicio extends javax.swing.JFrame {
    
    int xMouse,yMouse;

    /**
     * Creates new form HotelInter
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpnl = new javax.swing.JPanel();
        lblfondo = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblusuario1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        psContraseña = new javax.swing.JPasswordField();
        exxitpn = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        panexit = new javax.swing.JPanel();
        lblequis = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panEntrar = new javax.swing.JPanel();
        lblEntrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Camerum");
        setBackground(new java.awt.Color(0, 102, 153));
        setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bgpnl.setBackground(new java.awt.Color(0, 0, 0));
        bgpnl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bgpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario iTC\\Desktop\\imagenesProyecto\\edificioIni.png")); // NOI18N
        bgpnl.add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 220, 240));

        lblcontraseña.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblcontraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblcontraseña.setText("CONTRASEÑA");
        bgpnl.add(lblcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        bgpnl.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 40));

        lblusuario1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblusuario1.setForeground(new java.awt.Color(255, 255, 255));
        lblusuario1.setText("USUARIO");
        bgpnl.add(lblusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        bgpnl.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 40));

        psContraseña.setBackground(new java.awt.Color(0, 0, 0));
        psContraseña.setForeground(new java.awt.Color(255, 255, 255));
        psContraseña.setText("********");
        psContraseña.setBorder(null);
        psContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psContraseñaMousePressed(evt);
            }
        });
        psContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psContraseñaActionPerformed(evt);
            }
        });
        bgpnl.add(psContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 20));

        exxitpn.setBackground(new java.awt.Color(0, 0, 0));
        exxitpn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                exxitpnMouseDragged(evt);
            }
        });
        exxitpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exxitpnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout exxitpnLayout = new javax.swing.GroupLayout(exxitpn);
        exxitpn.setLayout(exxitpnLayout);
        exxitpnLayout.setHorizontalGroup(
            exxitpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        exxitpnLayout.setVerticalGroup(
            exxitpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bgpnl.add(exxitpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 30));

        txtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        bgpnl.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 20));

        panexit.setBackground(new java.awt.Color(0, 0, 0));
        panexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panexitMouseExited(evt);
            }
        });

        lblequis.setBackground(new java.awt.Color(255, 255, 0));
        lblequis.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblequis.setForeground(new java.awt.Color(255, 255, 255));
        lblequis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblequis.setText("X");
        lblequis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblequis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblequisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblequisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblequisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panexitLayout = new javax.swing.GroupLayout(panexit);
        panexit.setLayout(panexitLayout);
        panexitLayout.setHorizontalGroup(
            panexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblequis, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        panexitLayout.setVerticalGroup(
            panexitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblequis, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bgpnl.add(panexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 40));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CAMERUM HOTEL");
        bgpnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 40));

        panEntrar.setBackground(new java.awt.Color(0, 0, 0));
        panEntrar.setForeground(new java.awt.Color(255, 255, 255));

        lblEntrar.setBackground(new java.awt.Color(255, 255, 255));
        lblEntrar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        lblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        lblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntrar.setText("Entrar");
        lblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panEntrarLayout = new javax.swing.GroupLayout(panEntrar);
        panEntrar.setLayout(panEntrarLayout);
        panEntrarLayout.setHorizontalGroup(
            panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panEntrarLayout.setVerticalGroup(
            panEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgpnl.add(panEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpnl, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psContraseñaMousePressed
         if(String.valueOf(psContraseña.getPassword()).equals("********")){
           psContraseña.setText("");
           psContraseña.setForeground(Color.white);
         }
           if(txtUsuario.getText().isEmpty()){
        txtUsuario.setText("Ingrese su nombre de usuario");
        txtUsuario.setForeground(Color.white);
           }
    }//GEN-LAST:event_psContraseñaMousePressed

    private void exxitpnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exxitpnMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_exxitpnMousePressed

    private void exxitpnMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exxitpnMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse,y - yMouse);
        
    }//GEN-LAST:event_exxitpnMouseDragged

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void psContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psContraseñaActionPerformed

    private void panexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panexitMouseExited
        panexit.setBackground(Color.black);
    }//GEN-LAST:event_panexitMouseExited

    private void panexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panexitMouseEntered
        panexit.setBackground(Color.red);
    }//GEN-LAST:event_panexitMouseEntered

    private void panexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_panexitMouseClicked

    private void lblequisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblequisMouseExited
        panexit.setBackground(Color.black);
    }//GEN-LAST:event_lblequisMouseExited

    private void lblequisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblequisMouseEntered
        panexit.setBackground(Color.red);
    }//GEN-LAST:event_lblequisMouseEntered

    private void lblequisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblequisMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblequisMouseClicked

    private void lblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseEntered
     panEntrar.setBackground(Color.gray);
    }//GEN-LAST:event_lblEntrarMouseEntered

    private void lblEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseExited
        panEntrar.setBackground(Color.black);
    }//GEN-LAST:event_lblEntrarMouseExited

    private void lblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEntrarMouseClicked
        Procesos newframe= new Procesos();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgpnl;
    private javax.swing.JPanel exxitpn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblequis;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblusuario1;
    private javax.swing.JPanel panEntrar;
    private javax.swing.JPanel panexit;
    private javax.swing.JPasswordField psContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
